package cn.ponyzhang.server.mapper;

import cn.ponyzhang.server.entity.Blog;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.messaging.handler.annotation.Payload;

import java.util.Date;
import java.util.List;

@Mapper
public interface BlogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog
     *
     * @mbg.generated Fri Nov 12 10:49:57 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog
     *
     * @mbg.generated Fri Nov 12 10:49:57 CST 2021
     */
    int insert(Blog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog
     *
     * @mbg.generated Fri Nov 12 10:49:57 CST 2021
     */
    Blog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog
     *
     * @mbg.generated Fri Nov 12 10:49:57 CST 2021
     */
    List<Blog> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog
     *
     * @mbg.generated Fri Nov 12 10:49:57 CST 2021
     */

    int reduceByPrimaryKey(@Param("blogId") Integer id, @Param("date")Date date);

    int addByPrimaryKey(@Param("blogId") Integer id, @Param("date")Date date);
}