package cn.ponyzhang.server.mapper;

import cn.ponyzhang.server.entity.BookStock;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface BookStockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_stock
     *
     * @mbg.generated Wed Nov 10 15:20:22 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_stock
     *
     * @mbg.generated Wed Nov 10 15:20:22 CST 2021
     */
    int insert(BookStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_stock
     *
     * @mbg.generated Wed Nov 10 15:20:22 CST 2021
     */
    BookStock selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_stock
     *
     * @mbg.generated Wed Nov 10 15:20:22 CST 2021
     */
    List<BookStock> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_stock
     *
     * @mbg.generated Wed Nov 10 15:20:22 CST 2021
     */
    int updateByPrimaryKey(BookStock record);

    BookStock selectByBookNo(String bookNo);

    int updateStock(String bookNo);
}