package cn.ponyzhang.server.mapper;

import cn.ponyzhang.server.entity.BookRob;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface BookRobMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_rob
     *
     * @mbg.generated Wed Nov 10 15:20:22 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_rob
     *
     * @mbg.generated Wed Nov 10 15:20:22 CST 2021
     */
    int insert(BookRob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_rob
     *
     * @mbg.generated Wed Nov 10 15:20:22 CST 2021
     */
    BookRob selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_rob
     *
     * @mbg.generated Wed Nov 10 15:20:22 CST 2021
     */
    List<BookRob> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_rob
     *
     * @mbg.generated Wed Nov 10 15:20:22 CST 2021
     */
    int updateByPrimaryKey(BookRob record);

    BookRob selectByUserIdAndBookNo(@Param("userId") Integer userId,@Param("bookNo") String bookNo);
}