package cn.ponyzhang.server.mapper;

import cn.ponyzhang.server.entity.MqOrder;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface MqOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mq_order
     *
     * @mbg.generated Mon Nov 08 12:47:37 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mq_order
     *
     * @mbg.generated Mon Nov 08 12:47:37 CST 2021
     */
    int insert(MqOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mq_order
     *
     * @mbg.generated Mon Nov 08 12:47:37 CST 2021
     */
    MqOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mq_order
     *
     * @mbg.generated Mon Nov 08 12:47:37 CST 2021
     */
    List<MqOrder> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mq_order
     *
     * @mbg.generated Mon Nov 08 12:47:37 CST 2021
     */
    int updateByPrimaryKey(MqOrder record);
}