package cn.ponyzhang.server.mapper;

import cn.ponyzhang.server.dto.PraiseRankDto;
import cn.ponyzhang.server.entity.Praise;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.Date;
import java.util.List;

@Mapper
public interface PraiseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table praise
     *
     * @mbg.generated Fri Nov 12 10:49:57 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table praise
     *
     * @mbg.generated Fri Nov 12 10:49:57 CST 2021
     */
    int insert(Praise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table praise
     *
     * @mbg.generated Fri Nov 12 10:49:57 CST 2021
     */
    Praise selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table praise
     *
     * @mbg.generated Fri Nov 12 10:49:57 CST 2021
     */
    List<Praise> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table praise
     *
     * @mbg.generated Fri Nov 12 10:49:57 CST 2021
     */
    int updateByUserId(@Param("userId") Integer userId, @Param("status") Byte status, @Param("date")Date date);

    Praise selectByUserIdAndBlogId(@Param("userId") Integer userId,@Param("blogId") Integer blogId);

    List<PraiseRankDto> getPraiseRank();
}