package cn.ponyzhang.server.mapper;

import cn.ponyzhang.server.entity.UserAccount;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.math.BigDecimal;
import java.util.List;

@Mapper
public interface UserAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account
     *
     * @mbg.generated Mon Nov 08 20:19:23 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account
     *
     * @mbg.generated Mon Nov 08 20:19:23 CST 2021
     */
    int insert(UserAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account
     *
     * @mbg.generated Mon Nov 08 20:19:23 CST 2021
     */
    UserAccount selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account
     *
     * @mbg.generated Mon Nov 08 20:19:23 CST 2021
     */
    List<UserAccount> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account
     *
     * @mbg.generated Mon Nov 08 20:19:23 CST 2021
     */
    int updateByPrimaryKey(UserAccount record);


    UserAccount selectByUserId(Integer userId);

    UserAccount selectByUserIdAndLock(Integer userId);

    int updateByUserIdAndAmount(@Param("id") Integer id, @Param("money")BigDecimal money);

    int updateByUserIdAndAmountAndVersion(@Param("id") Integer id, @Param("money")BigDecimal money,@Param("version")Integer version);

    int updateAmountLock(@Param("id") Integer id, @Param("money")BigDecimal money);
}