package cn.ponyzhang.server.mapper;

import cn.ponyzhang.server.entity.UserOrder;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import javax.annotation.ManagedBean;
import java.util.List;

@Mapper
public interface UserOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_order
     *
     * @mbg.generated Mon Nov 08 12:47:37 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_order
     *
     * @mbg.generated Mon Nov 08 12:47:37 CST 2021
     */
    int insert(UserOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_order
     *
     * @mbg.generated Mon Nov 08 12:47:37 CST 2021
     */
    UserOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_order
     *
     * @mbg.generated Mon Nov 08 12:47:37 CST 2021
     */
    List<UserOrder> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_order
     *
     * @mbg.generated Mon Nov 08 12:47:37 CST 2021
     */
    int updateByPrimaryKey(UserOrder record);

    UserOrder selectByIdAndStatus(@Param("id") Integer id, @Param("status") Integer status);

}