package cn.ponyzhang.server.mapper;

import cn.ponyzhang.server.entity.UserReg;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface UserRegMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_reg
     *
     * @mbg.generated Wed Nov 10 09:31:37 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_reg
     *
     * @mbg.generated Wed Nov 10 09:31:37 CST 2021
     */
    int insert(UserReg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_reg
     *
     * @mbg.generated Wed Nov 10 09:31:37 CST 2021
     */
    UserReg selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_reg
     *
     * @mbg.generated Wed Nov 10 09:31:37 CST 2021
     */
    List<UserReg> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_reg
     *
     * @mbg.generated Wed Nov 10 09:31:37 CST 2021
     */
    int updateByPrimaryKey(UserReg record);

    UserReg selectByUserName(String userName);
}