package cn.ponyzhang.server.entity;

import java.util.Date;

public class Blog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.id
     *
     * @mbg.generated Fri Nov 12 10:49:57 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.title
     *
     * @mbg.generated Fri Nov 12 10:49:57 CST 2021
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.praise_count
     *
     * @mbg.generated Fri Nov 12 10:49:57 CST 2021
     */
    private Integer praiseCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.is_active
     *
     * @mbg.generated Fri Nov 12 10:49:57 CST 2021
     */
    private Byte isActive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.create_time
     *
     * @mbg.generated Fri Nov 12 10:49:57 CST 2021
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.update_time
     *
     * @mbg.generated Fri Nov 12 10:49:57 CST 2021
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.id
     *
     * @return the value of blog.id
     *
     * @mbg.generated Fri Nov 12 10:49:57 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.id
     *
     * @param id the value for blog.id
     *
     * @mbg.generated Fri Nov 12 10:49:57 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.title
     *
     * @return the value of blog.title
     *
     * @mbg.generated Fri Nov 12 10:49:57 CST 2021
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.title
     *
     * @param title the value for blog.title
     *
     * @mbg.generated Fri Nov 12 10:49:57 CST 2021
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.praise_count
     *
     * @return the value of blog.praise_count
     *
     * @mbg.generated Fri Nov 12 10:49:57 CST 2021
     */
    public Integer getPraiseCount() {
        return praiseCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.praise_count
     *
     * @param praiseCount the value for blog.praise_count
     *
     * @mbg.generated Fri Nov 12 10:49:57 CST 2021
     */
    public void setPraiseCount(Integer praiseCount) {
        this.praiseCount = praiseCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.is_active
     *
     * @return the value of blog.is_active
     *
     * @mbg.generated Fri Nov 12 10:49:57 CST 2021
     */
    public Byte getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.is_active
     *
     * @param isActive the value for blog.is_active
     *
     * @mbg.generated Fri Nov 12 10:49:57 CST 2021
     */
    public void setIsActive(Byte isActive) {
        this.isActive = isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.create_time
     *
     * @return the value of blog.create_time
     *
     * @mbg.generated Fri Nov 12 10:49:57 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.create_time
     *
     * @param createTime the value for blog.create_time
     *
     * @mbg.generated Fri Nov 12 10:49:57 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.update_time
     *
     * @return the value of blog.update_time
     *
     * @mbg.generated Fri Nov 12 10:49:57 CST 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.update_time
     *
     * @param updateTime the value for blog.update_time
     *
     * @mbg.generated Fri Nov 12 10:49:57 CST 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}