package cn.ponyzhang.server.entity;

import java.util.Date;

public class BookRob {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_rob.id
     *
     * @mbg.generated Wed Nov 10 15:20:22 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_rob.user_id
     *
     * @mbg.generated Wed Nov 10 15:20:22 CST 2021
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_rob.book_no
     *
     * @mbg.generated Wed Nov 10 15:20:22 CST 2021
     */
    private String bookNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_rob.rob_time
     *
     * @mbg.generated Wed Nov 10 15:20:22 CST 2021
     */
    private Date robTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_rob.id
     *
     * @return the value of book_rob.id
     *
     * @mbg.generated Wed Nov 10 15:20:22 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_rob.id
     *
     * @param id the value for book_rob.id
     *
     * @mbg.generated Wed Nov 10 15:20:22 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_rob.user_id
     *
     * @return the value of book_rob.user_id
     *
     * @mbg.generated Wed Nov 10 15:20:22 CST 2021
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_rob.user_id
     *
     * @param userId the value for book_rob.user_id
     *
     * @mbg.generated Wed Nov 10 15:20:22 CST 2021
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_rob.book_no
     *
     * @return the value of book_rob.book_no
     *
     * @mbg.generated Wed Nov 10 15:20:22 CST 2021
     */
    public String getBookNo() {
        return bookNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_rob.book_no
     *
     * @param bookNo the value for book_rob.book_no
     *
     * @mbg.generated Wed Nov 10 15:20:22 CST 2021
     */
    public void setBookNo(String bookNo) {
        this.bookNo = bookNo == null ? null : bookNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_rob.rob_time
     *
     * @return the value of book_rob.rob_time
     *
     * @mbg.generated Wed Nov 10 15:20:22 CST 2021
     */
    public Date getRobTime() {
        return robTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_rob.rob_time
     *
     * @param robTime the value for book_rob.rob_time
     *
     * @mbg.generated Wed Nov 10 15:20:22 CST 2021
     */
    public void setRobTime(Date robTime) {
        this.robTime = robTime;
    }
}