package cn.ponyzhang.server.entity;

import java.util.Date;

public class Praise {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column praise.id
     *
     * @mbg.generated Fri Nov 12 10:49:57 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column praise.blog_id
     *
     * @mbg.generated Fri Nov 12 10:49:57 CST 2021
     */
    private Integer blogId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column praise.user_id
     *
     * @mbg.generated Fri Nov 12 10:49:57 CST 2021
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column praise.praise_time
     *
     * @mbg.generated Fri Nov 12 10:49:57 CST 2021
     */
    private Date praiseTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column praise.status
     *
     * @mbg.generated Fri Nov 12 10:49:57 CST 2021
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column praise.is_active
     *
     * @mbg.generated Fri Nov 12 10:49:57 CST 2021
     */
    private Byte isActive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column praise.create_time
     *
     * @mbg.generated Fri Nov 12 10:49:57 CST 2021
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column praise.update_time
     *
     * @mbg.generated Fri Nov 12 10:49:57 CST 2021
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column praise.id
     *
     * @return the value of praise.id
     *
     * @mbg.generated Fri Nov 12 10:49:57 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column praise.id
     *
     * @param id the value for praise.id
     *
     * @mbg.generated Fri Nov 12 10:49:57 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column praise.blog_id
     *
     * @return the value of praise.blog_id
     *
     * @mbg.generated Fri Nov 12 10:49:57 CST 2021
     */
    public Integer getBlogId() {
        return blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column praise.blog_id
     *
     * @param blogId the value for praise.blog_id
     *
     * @mbg.generated Fri Nov 12 10:49:57 CST 2021
     */
    public void setBlogId(Integer blogId) {
        this.blogId = blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column praise.user_id
     *
     * @return the value of praise.user_id
     *
     * @mbg.generated Fri Nov 12 10:49:57 CST 2021
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column praise.user_id
     *
     * @param userId the value for praise.user_id
     *
     * @mbg.generated Fri Nov 12 10:49:57 CST 2021
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column praise.praise_time
     *
     * @return the value of praise.praise_time
     *
     * @mbg.generated Fri Nov 12 10:49:57 CST 2021
     */
    public Date getPraiseTime() {
        return praiseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column praise.praise_time
     *
     * @param praiseTime the value for praise.praise_time
     *
     * @mbg.generated Fri Nov 12 10:49:57 CST 2021
     */
    public void setPraiseTime(Date praiseTime) {
        this.praiseTime = praiseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column praise.status
     *
     * @return the value of praise.status
     *
     * @mbg.generated Fri Nov 12 10:49:57 CST 2021
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column praise.status
     *
     * @param status the value for praise.status
     *
     * @mbg.generated Fri Nov 12 10:49:57 CST 2021
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column praise.is_active
     *
     * @return the value of praise.is_active
     *
     * @mbg.generated Fri Nov 12 10:49:57 CST 2021
     */
    public Byte getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column praise.is_active
     *
     * @param isActive the value for praise.is_active
     *
     * @mbg.generated Fri Nov 12 10:49:57 CST 2021
     */
    public void setIsActive(Byte isActive) {
        this.isActive = isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column praise.create_time
     *
     * @return the value of praise.create_time
     *
     * @mbg.generated Fri Nov 12 10:49:57 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column praise.create_time
     *
     * @param createTime the value for praise.create_time
     *
     * @mbg.generated Fri Nov 12 10:49:57 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column praise.update_time
     *
     * @return the value of praise.update_time
     *
     * @mbg.generated Fri Nov 12 10:49:57 CST 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column praise.update_time
     *
     * @param updateTime the value for praise.update_time
     *
     * @mbg.generated Fri Nov 12 10:49:57 CST 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}