package cn.ponyzhang.server.entity;

import java.util.Date;

public class SysLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.id
     *
     * @mbg.generated Mon Nov 08 12:39:03 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.user_id
     *
     * @mbg.generated Mon Nov 08 12:39:03 CST 2021
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.module
     *
     * @mbg.generated Mon Nov 08 12:39:03 CST 2021
     */
    private String module;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.data
     *
     * @mbg.generated Mon Nov 08 12:39:03 CST 2021
     */
    private String data;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.memo
     *
     * @mbg.generated Mon Nov 08 12:39:03 CST 2021
     */
    private String memo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.create_time
     *
     * @mbg.generated Mon Nov 08 12:39:03 CST 2021
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.id
     *
     * @return the value of sys_log.id
     *
     * @mbg.generated Mon Nov 08 12:39:03 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.id
     *
     * @param id the value for sys_log.id
     *
     * @mbg.generated Mon Nov 08 12:39:03 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.user_id
     *
     * @return the value of sys_log.user_id
     *
     * @mbg.generated Mon Nov 08 12:39:03 CST 2021
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.user_id
     *
     * @param userId the value for sys_log.user_id
     *
     * @mbg.generated Mon Nov 08 12:39:03 CST 2021
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.module
     *
     * @return the value of sys_log.module
     *
     * @mbg.generated Mon Nov 08 12:39:03 CST 2021
     */
    public String getModule() {
        return module;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.module
     *
     * @param module the value for sys_log.module
     *
     * @mbg.generated Mon Nov 08 12:39:03 CST 2021
     */
    public void setModule(String module) {
        this.module = module == null ? null : module.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.data
     *
     * @return the value of sys_log.data
     *
     * @mbg.generated Mon Nov 08 12:39:03 CST 2021
     */
    public String getData() {
        return data;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.data
     *
     * @param data the value for sys_log.data
     *
     * @mbg.generated Mon Nov 08 12:39:03 CST 2021
     */
    public void setData(String data) {
        this.data = data == null ? null : data.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.memo
     *
     * @return the value of sys_log.memo
     *
     * @mbg.generated Mon Nov 08 12:39:03 CST 2021
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.memo
     *
     * @param memo the value for sys_log.memo
     *
     * @mbg.generated Mon Nov 08 12:39:03 CST 2021
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.create_time
     *
     * @return the value of sys_log.create_time
     *
     * @mbg.generated Mon Nov 08 12:39:03 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.create_time
     *
     * @param createTime the value for sys_log.create_time
     *
     * @mbg.generated Mon Nov 08 12:39:03 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}