package cn.ponyzhang.server.entity;

import java.util.Date;

public class UserReg {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_reg.id
     *
     * @mbg.generated Wed Nov 10 11:18:07 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_reg.user_name
     *
     * @mbg.generated Wed Nov 10 11:18:07 CST 2021
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_reg.password
     *
     * @mbg.generated Wed Nov 10 11:18:07 CST 2021
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_reg.create_time
     *
     * @mbg.generated Wed Nov 10 11:18:07 CST 2021
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_reg.id
     *
     * @return the value of user_reg.id
     *
     * @mbg.generated Wed Nov 10 11:18:07 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_reg.id
     *
     * @param id the value for user_reg.id
     *
     * @mbg.generated Wed Nov 10 11:18:07 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_reg.user_name
     *
     * @return the value of user_reg.user_name
     *
     * @mbg.generated Wed Nov 10 11:18:07 CST 2021
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_reg.user_name
     *
     * @param userName the value for user_reg.user_name
     *
     * @mbg.generated Wed Nov 10 11:18:07 CST 2021
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_reg.password
     *
     * @return the value of user_reg.password
     *
     * @mbg.generated Wed Nov 10 11:18:07 CST 2021
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_reg.password
     *
     * @param password the value for user_reg.password
     *
     * @mbg.generated Wed Nov 10 11:18:07 CST 2021
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_reg.create_time
     *
     * @return the value of user_reg.create_time
     *
     * @mbg.generated Wed Nov 10 11:18:07 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_reg.create_time
     *
     * @param createTime the value for user_reg.create_time
     *
     * @mbg.generated Wed Nov 10 11:18:07 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}