package cn.ponyzhang.server.entity;

import java.util.Date;

public class UserOrder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_order.id
     *
     * @mbg.generated Mon Nov 08 12:47:37 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_order.order_no
     *
     * @mbg.generated Mon Nov 08 12:47:37 CST 2021
     */
    private String orderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_order.user_id
     *
     * @mbg.generated Mon Nov 08 12:47:37 CST 2021
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_order.status
     *
     * @mbg.generated Mon Nov 08 12:47:37 CST 2021
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_order.is_active
     *
     * @mbg.generated Mon Nov 08 12:47:37 CST 2021
     */
    private Integer isActive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_order.create_time
     *
     * @mbg.generated Mon Nov 08 12:47:37 CST 2021
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_order.update_time
     *
     * @mbg.generated Mon Nov 08 12:47:37 CST 2021
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order.id
     *
     * @return the value of user_order.id
     *
     * @mbg.generated Mon Nov 08 12:47:37 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order.id
     *
     * @param id the value for user_order.id
     *
     * @mbg.generated Mon Nov 08 12:47:37 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order.order_no
     *
     * @return the value of user_order.order_no
     *
     * @mbg.generated Mon Nov 08 12:47:37 CST 2021
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order.order_no
     *
     * @param orderNo the value for user_order.order_no
     *
     * @mbg.generated Mon Nov 08 12:47:37 CST 2021
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order.user_id
     *
     * @return the value of user_order.user_id
     *
     * @mbg.generated Mon Nov 08 12:47:37 CST 2021
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order.user_id
     *
     * @param userId the value for user_order.user_id
     *
     * @mbg.generated Mon Nov 08 12:47:37 CST 2021
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order.status
     *
     * @return the value of user_order.status
     *
     * @mbg.generated Mon Nov 08 12:47:37 CST 2021
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order.status
     *
     * @param status the value for user_order.status
     *
     * @mbg.generated Mon Nov 08 12:47:37 CST 2021
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order.is_active
     *
     * @return the value of user_order.is_active
     *
     * @mbg.generated Mon Nov 08 12:47:37 CST 2021
     */
    public Integer getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order.is_active
     *
     * @param isActive the value for user_order.is_active
     *
     * @mbg.generated Mon Nov 08 12:47:37 CST 2021
     */
    public void setIsActive(Integer isActive) {
        this.isActive = isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order.create_time
     *
     * @return the value of user_order.create_time
     *
     * @mbg.generated Mon Nov 08 12:47:37 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order.create_time
     *
     * @param createTime the value for user_order.create_time
     *
     * @mbg.generated Mon Nov 08 12:47:37 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order.update_time
     *
     * @return the value of user_order.update_time
     *
     * @mbg.generated Mon Nov 08 12:47:37 CST 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order.update_time
     *
     * @param updateTime the value for user_order.update_time
     *
     * @mbg.generated Mon Nov 08 12:47:37 CST 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}